# ruff: noqa: E402, I001
"""Meta walk-forward selection for layered low-correlation overlays.

The fixed layered overlay grid is useful for finding new return sources, but it
still selects overlay rules with full-sample hindsight. This script performs a
stricter meta-level walk-forward check:

- candidate daily paths are generated by the layered-overlay script;
- each test year uses only earlier out-of-sample years to select one candidate;
- 2020 has no prior OOS evidence, so it uses the preset base-only path;
- selected overlay rules are frozen for the next test year.

Run:
    .venv/bin/python examples/signals_dev/validate_daily_cta_layered_overlay_meta_walk_forward.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from validate_daily_cta_layered_low_corr_overlay import (  # noqa: E402
    BASE_PRESETS,
    OUTPUT_DIR as LAYERED_OUTPUT_DIR,
    TARGET_ANNUAL_RETURN,
    TARGET_MAX_DRAWDOWN,
    build_overlay_paths,
    evaluate_window_stress,
)
from validate_daily_cta_walk_forward import annualized_stats, summarize_yearly  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
OUTPUT_DIR = ROOT / "examples" / "results" / "daily_cta_layered_overlay_meta_walk_forward"
YEARS = tuple(range(2020, 2027))


def candidate_filter(summary: pd.DataFrame, policy: str, base_preset: str) -> pd.Series:
    """Return a boolean mask for a meta-selection candidate universe."""
    mask = summary["base_preset"].eq(base_preset) | summary["overlay_mode"].eq("base_only")
    if policy == "all":
        return mask
    if policy == "gold_additive":
        return mask & (
            summary["overlay_mode"].eq("base_only")
            | (summary["overlay_mode"].eq("additive") & summary["budget"].isin(["gold", "gold_bond"]))
        )
    if policy == "gold_conservative":
        return mask & (
            summary["overlay_mode"].eq("base_only")
            | (
                summary["overlay_mode"].eq("additive")
                & summary["budget"].isin(["gold", "gold_bond"])
                & summary["overlay_weight"].between(0.08, 0.20)
            )
            | (
                summary["overlay_mode"].eq("replacement")
                & summary["budget"].eq("gold")
                & summary["overlay_weight"].le(0.10)
            )
        )
    if policy == "commodity_conservative":
        return mask & (
            summary["overlay_mode"].eq("base_only")
            | (
                summary["overlay_mode"].eq("additive")
                & summary["budget"].isin(["commodity", "commodity_gold", "inflation_pack"])
                & summary["overlay_weight"].between(0.08, 0.20)
            )
        )
    if policy == "energy_conservative":
        return mask & (
            summary["overlay_mode"].eq("base_only")
            | (
                summary["overlay_mode"].eq("additive")
                & summary["budget"].isin(["energy", "commodity_gold", "inflation_pack"])
                & summary["overlay_weight"].between(0.08, 0.30)
            )
        )
    if policy == "weak_window_conservative":
        return mask & (
            summary["overlay_mode"].eq("base_only")
            | (
                summary["overlay_mode"].eq("additive")
                & summary["budget"].isin(["energy", "commodity_gold", "resource_gold", "agri", "gold"])
                & summary["overlay_weight"].between(0.10, 0.30)
            )
            | (
                summary["overlay_mode"].eq("replacement")
                & summary["budget"].isin(["agri", "gold"])
                & summary["overlay_weight"].between(0.20, 0.30)
            )
        )
    if policy == "bond_conservative":
        return mask & (
            summary["overlay_mode"].eq("base_only")
            | (
                summary["overlay_mode"].eq("replacement")
                & summary["budget"].isin(["bond_plus", "bond_plus_gold", "bond_plus_commodity"])
                & summary["overlay_weight"].between(0.05, 0.30)
            )
            | (
                summary["overlay_mode"].eq("additive")
                & summary["budget"].isin(["bond_plus", "bond_plus_gold", "bond_plus_commodity"])
                & summary["overlay_weight"].between(0.05, 0.20)
            )
        )
    if policy == "inflation_conservative":
        return mask & (
            summary["overlay_mode"].eq("base_only")
            | (
                summary["overlay_mode"].eq("additive")
                & summary["budget"].isin(
                    [
                        "gold",
                        "gold_bond",
                        "commodity",
                        "commodity_gold",
                        "inflation_pack",
                        "bond_plus_gold",
                        "bond_plus_commodity",
                    ]
                )
                & summary["overlay_weight"].between(0.08, 0.20)
            )
        )
    if policy == "low_drawdown":
        return mask & (
            summary["overlay_mode"].eq("base_only")
            | summary["overlay_mode"].eq("replacement")
            | (
                summary["overlay_mode"].eq("additive")
                & summary["budget"].isin(["gold", "gold_bond", "defensive"])
                & summary["overlay_weight"].le(0.15)
            )
        )
    raise ValueError(f"Unsupported policy: {policy}")


def choose_candidate(
    yearly: pd.DataFrame,
    candidate_labels: list[str],
    train_years: list[int],
    min_train_years: int,
) -> dict:
    """Choose one label using prior years only."""
    if len(train_years) < min_train_years:
        return {
            "label": None,
            "reason": "base_until_min_train_years",
            "train_years": ",".join(str(x) for x in train_years),
            "train_candidates": 0,
            "eligible_candidates": 0,
        }

    rows = []
    for label in candidate_labels:
        part = yearly[(yearly["label"] == label) & (yearly["year"].isin(train_years))].copy()
        if part.empty:
            continue
        cumulative = float((1 + part["return"]).prod() - 1)
        annual_return = float((1 + cumulative) ** (1 / len(part)) - 1)
        max_drawdown = float(part["max_drawdown"].min())
        stats = {
            "label": label,
            "annual_return": annual_return,
            "cumulative_return": cumulative,
            "final_nav": float(1 + cumulative),
            "max_drawdown": max_drawdown,
            "calmar": float(annual_return / abs(max_drawdown)) if max_drawdown < 0 else float("nan"),
            "avg_abs_weight": float(part["avg_abs_weight"].mean()),
            "max_abs_weight": float(part["max_abs_weight"].max()),
            "train_loss_years": int((part["return"] < 0).sum()),
        }
        stats["score"] = (
            stats["calmar"]
            + 0.75 * stats["annual_return"]
            - 3.0 * max(0.0, abs(stats["max_drawdown"]) - 0.08)
            - 0.05 * stats["train_loss_years"]
            - 0.02 * stats["max_abs_weight"]
        )
        rows.append(stats)
    ranked = pd.DataFrame(rows)
    if ranked.empty:
        return {
            "label": None,
            "reason": "no_train_rows",
            "train_years": ",".join(str(x) for x in train_years),
            "train_candidates": 0,
            "eligible_candidates": 0,
        }

    eligible = ranked[
        (ranked["annual_return"] > 0)
        & (ranked["max_drawdown"] >= TARGET_MAX_DRAWDOWN)
        & (ranked["train_loss_years"] <= max(1, len(train_years) // 2))
    ].copy()
    if eligible.empty:
        eligible = ranked[ranked["max_drawdown"] >= -0.12].copy()
    if eligible.empty:
        eligible = ranked.copy()
    selected = eligible.sort_values(["score", "calmar", "annual_return"], ascending=False).iloc[0].to_dict()
    selected["reason"] = "selected_by_prior_oos"
    selected["train_years"] = ",".join(str(x) for x in train_years)
    selected["train_candidates"] = int(len(ranked))
    selected["eligible_candidates"] = int(len(eligible))
    return selected


def stitch_meta_path(
    daily: pd.DataFrame,
    summary: pd.DataFrame,
    yearly: pd.DataFrame,
    base_preset: str,
    policy: str,
    min_train_years: int,
    train_window: str,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Stitch one meta walk-forward path from prior-year selections."""
    universe = summary[candidate_filter(summary, policy, base_preset)].copy()
    labels = universe["label"].tolist()
    base_label = f"{base_preset}_base_only"
    selected_rows = []
    daily_parts = []

    for year in YEARS:
        if train_window == "expanding":
            train_years = [x for x in YEARS if x < year]
        elif train_window == "rolling3":
            train_years = [x for x in YEARS if year - 3 <= x < year]
        else:
            raise ValueError(f"Unsupported train_window: {train_window}")

        selected = choose_candidate(yearly, labels, train_years, min_train_years)
        selected_label = selected["label"] or base_label
        test = daily[(daily["label"] == selected_label) & (daily["dt"].dt.year == year)].copy()
        test["meta_label"] = f"{base_preset}_{policy}_min{min_train_years}_{train_window}_meta_walk_forward"
        test["selected_label"] = selected_label
        test["test_year"] = year
        daily_parts.append(test)
        selected_rows.append(
            {
                "meta_label": test["meta_label"].iloc[0],
                "test_year": year,
                "selected_label": selected_label,
                "base_label": base_label,
                "policy": policy,
                "base_preset": base_preset,
                "min_train_years": min_train_years,
                "train_window": train_window,
                **{f"train_{key}": value for key, value in selected.items() if key != "label"},
            }
        )

    stitched = pd.concat(daily_parts, ignore_index=True).sort_values("dt").reset_index(drop=True)
    stitched["nav"] = (1 + stitched["ret"]).cumprod()
    stitched["drawdown"] = stitched["nav"] / stitched["nav"].cummax() - 1
    selected_df = pd.DataFrame(selected_rows)
    return stitched, selected_df


def summarize_meta_path(daily: pd.DataFrame, meta_label: str) -> dict:
    """Summarize a stitched meta path."""
    stats = annualized_stats(daily["dt"].reset_index(drop=True), daily["ret"].to_numpy(), daily["weight"].to_numpy())
    pre = daily[daily["dt"].dt.year <= 2025].copy()
    pre_stats = annualized_stats(pre["dt"].reset_index(drop=True), pre["ret"].to_numpy(), pre["weight"].to_numpy())
    stats.update(
        {
            "meta_label": meta_label,
            "pre2026_annual_return": pre_stats["annual_return"],
            "pre2026_max_drawdown": pre_stats["max_drawdown"],
            "pass_full_and_pre2026": bool(
                stats["annual_return"] >= TARGET_ANNUAL_RETURN
                and stats["max_drawdown"] >= TARGET_MAX_DRAWDOWN
                and pre_stats["annual_return"] >= TARGET_ANNUAL_RETURN
                and pre_stats["max_drawdown"] >= TARGET_MAX_DRAWDOWN
            ),
        }
    )
    return stats


def save_nav_plot(daily: pd.DataFrame, labels: list[str]) -> None:
    """Save a net-value plot for top meta candidates."""
    import plotly.graph_objects as go

    fig = go.Figure()
    for label in labels:
        part = daily[daily["meta_label"] == label].copy()
        fig.add_trace(go.Scatter(x=part["dt"], y=part["nav"], mode="lines", name=label))
    fig.update_layout(
        title="Layered overlay meta walk-forward candidates",
        xaxis_title="date",
        yaxis_title="net value",
        template="plotly_white",
    )
    fig.write_html(OUTPUT_DIR / "meta_walk_forward_nav.html", include_plotlyjs="cdn")


def build_meta_blends(daily: pd.DataFrame, summary: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """Blend the best gold and commodity meta paths with fixed weights."""
    gold_pool = summary[summary["meta_label"].str.contains("gold_conservative")].copy()
    commodity_pool = summary[summary["meta_label"].str.contains("commodity_conservative")].copy()
    gold_pool = gold_pool[gold_pool["pass_full_and_pre2026"]]
    commodity_pool = commodity_pool[commodity_pool["pass_full_and_pre2026"]]
    if gold_pool.empty or commodity_pool.empty:
        return pd.DataFrame(), pd.DataFrame(), pd.DataFrame()

    gold_label = gold_pool.sort_values(["annual_return", "stress_pass_rate"], ascending=False).iloc[0]["meta_label"]
    commodity_label = commodity_pool.sort_values(["stress_pass_rate", "annual_return"], ascending=False).iloc[0][
        "meta_label"
    ]
    gold = daily[daily["meta_label"] == gold_label][["dt", "ret", "weight"]].rename(
        columns={"ret": "gold_ret", "weight": "gold_weight"}
    )
    commodity = daily[daily["meta_label"] == commodity_label][["dt", "ret", "weight"]].rename(
        columns={"ret": "commodity_ret", "weight": "commodity_weight"}
    )
    joined = gold.merge(commodity, on="dt", how="inner")

    daily_rows = []
    summary_rows = []
    stress_rows = []
    for commodity_weight in [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]:
        gold_weight = 1 - commodity_weight
        path = joined.copy()
        path["ret"] = gold_weight * path["gold_ret"] + commodity_weight * path["commodity_ret"]
        path["weight"] = gold_weight * path["gold_weight"].abs() + commodity_weight * path["commodity_weight"].abs()
        blend_label = f"blend_gold_{gold_weight:.1f}_commodity_{commodity_weight:.1f}"
        path["meta_label"] = blend_label
        path["gold_meta_label"] = gold_label
        path["commodity_meta_label"] = commodity_label
        path["gold_weight"] = gold_weight
        path["commodity_weight"] = commodity_weight
        path["nav"] = (1 + path["ret"]).cumprod()
        path["drawdown"] = path["nav"] / path["nav"].cummax() - 1
        daily_rows.append(path)

        stats = summarize_meta_path(path, blend_label)
        stress = evaluate_window_stress(path.rename(columns={"meta_label": "label"}), blend_label)
        stats.update(
            {
                "gold_meta_label": gold_label,
                "commodity_meta_label": commodity_label,
                "gold_weight": gold_weight,
                "commodity_weight": commodity_weight,
                "stress_windows": int(len(stress)),
                "stress_pass_rate": float(stress["pass_20_10"].mean()),
                "stress_annual_median": float(stress["annual_return"].median()),
                "stress_mdd_median": float(stress["max_drawdown"].median()),
            }
        )
        summary_rows.append(stats)
        stress["meta_label"] = blend_label
        stress_rows.append(stress)

    return (
        pd.DataFrame(summary_rows),
        pd.concat(daily_rows, ignore_index=True),
        pd.concat(stress_rows, ignore_index=True),
    )


def main() -> None:
    """Run meta-level walk-forward overlay selection."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    summary, yearly_candidates, daily, _ = build_overlay_paths()
    daily["dt"] = pd.to_datetime(daily["dt"]).dt.tz_localize(None)

    meta_daily_rows = []
    selected_rows = []
    summary_rows = []
    yearly_rows = []
    stress_rows = []

    for base_preset in BASE_PRESETS:
        for policy in [
            "all",
            "gold_additive",
            "gold_conservative",
            "commodity_conservative",
            "inflation_conservative",
            "low_drawdown",
        ]:
            for min_train_years in [1, 2, 3]:
                for train_window in ["expanding", "rolling3"]:
                    meta_daily, selected = stitch_meta_path(
                        daily, summary, yearly_candidates, base_preset, policy, min_train_years, train_window
                    )
                    meta_label = meta_daily["meta_label"].iloc[0]
                    meta_daily_rows.append(meta_daily)
                    selected_rows.append(selected)
                    summary_rows.append(
                        {
                            **summarize_meta_path(meta_daily, meta_label),
                            "base_preset": base_preset,
                            "policy": policy,
                            "min_train_years": min_train_years,
                            "train_window": train_window,
                        }
                    )
                    yearly = summarize_yearly(meta_daily[["dt", "ret", "weight"]])
                    yearly["meta_label"] = meta_label
                    yearly["base_preset"] = base_preset
                    yearly["policy"] = policy
                    yearly["min_train_years"] = min_train_years
                    yearly["train_window"] = train_window
                    yearly_rows.append(yearly)
                    stress = evaluate_window_stress(meta_daily.rename(columns={"meta_label": "label"}), meta_label)
                    stress["meta_label"] = meta_label
                    stress_rows.append(stress)

    daily_out = pd.concat(meta_daily_rows, ignore_index=True)
    selected_out = pd.concat(selected_rows, ignore_index=True)
    summary_out = pd.DataFrame(summary_rows)
    yearly_out = pd.concat(yearly_rows, ignore_index=True)
    stress_out = pd.concat(stress_rows, ignore_index=True)
    stress_agg = (
        stress_out.groupby("meta_label")
        .agg(
            stress_windows=("pass_20_10", "size"),
            stress_pass_rate=("pass_20_10", "mean"),
            stress_annual_median=("annual_return", "median"),
            stress_mdd_median=("max_drawdown", "median"),
        )
        .reset_index()
    )
    summary_out = summary_out.merge(stress_agg, on="meta_label", how="left")
    top = summary_out.sort_values(
        ["pass_full_and_pre2026", "stress_pass_rate", "annual_return", "max_drawdown"],
        ascending=[False, False, False, False],
    )
    blend_summary, blend_daily, blend_stress = build_meta_blends(daily_out, summary_out)
    if not blend_summary.empty:
        blend_top = blend_summary.sort_values(
            ["stress_pass_rate", "annual_return", "max_drawdown"], ascending=[False, False, False]
        )
        blend_summary.to_csv(OUTPUT_DIR / "meta_walk_forward_blend_summary.csv", index=False, encoding="utf-8-sig")
        blend_daily[blend_daily["meta_label"].isin(blend_top["meta_label"].head(5))].to_csv(
            OUTPUT_DIR / "meta_walk_forward_blend_daily_top5.csv", index=False, encoding="utf-8-sig"
        )
        blend_stress.to_csv(OUTPUT_DIR / "meta_walk_forward_blend_window_stress.csv", index=False, encoding="utf-8-sig")

    summary_out.to_csv(OUTPUT_DIR / "meta_walk_forward_summary.csv", index=False, encoding="utf-8-sig")
    selected_out.to_csv(OUTPUT_DIR / "meta_walk_forward_selected_by_year.csv", index=False, encoding="utf-8-sig")
    yearly_out.to_csv(OUTPUT_DIR / "meta_walk_forward_yearly.csv", index=False, encoding="utf-8-sig")
    stress_out.to_csv(OUTPUT_DIR / "meta_walk_forward_window_stress.csv", index=False, encoding="utf-8-sig")
    daily_out[daily_out["meta_label"].isin(top["meta_label"].head(12))].to_csv(
        OUTPUT_DIR / "meta_walk_forward_daily_top12.csv", index=False, encoding="utf-8-sig"
    )
    top.head(20).to_csv(OUTPUT_DIR / "meta_walk_forward_top20.csv", index=False, encoding="utf-8-sig")
    save_nav_plot(daily_out, top["meta_label"].head(8).tolist())

    print("Top meta walk-forward candidates:")
    print(
        top[
            [
                "meta_label",
                "annual_return",
                "max_drawdown",
                "pre2026_annual_return",
                "pre2026_max_drawdown",
                "stress_pass_rate",
                "stress_annual_median",
                "stress_mdd_median",
                "pass_full_and_pre2026",
            ]
        ]
        .head(20)
        .to_string(index=False)
    )
    if not blend_summary.empty:
        print("\nTop meta blends:")
        print(
            blend_summary.sort_values(
                ["stress_pass_rate", "annual_return", "max_drawdown"], ascending=[False, False, False]
            )[
                [
                    "meta_label",
                    "annual_return",
                    "max_drawdown",
                    "pre2026_annual_return",
                    "pre2026_max_drawdown",
                    "stress_pass_rate",
                    "stress_annual_median",
                    "stress_mdd_median",
                    "pass_full_and_pre2026",
                ]
            ]
            .head(10)
            .to_string(index=False)
        )
    print(f"\nfixed-layered-output: {LAYERED_OUTPUT_DIR}")
    print(f"outputs: {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
